on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: revgen.azurecr.io
        username: ${{ secrets.acr_revgen_username }}
        password: ${{ secrets.acr_revgen_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t revgen.azurecr.io/locman:${{ github.sha }}
        docker push revgen.azurecr.io/locman:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_locman_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep locman061d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace locman061d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: locman061d
        container-registry-url: revgen.azurecr.io
        container-registry-username: ${{ secrets.acr_revgen_username }}
        container-registry-password: ${{ secrets.acr_revgen_password }}
        secret-name: locmandockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: locman061d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          revgen.azurecr.io/locman:${{ github.sha }}
        imagepullsecrets: |
          locmandockerauth